version: '3.8'

services:
  pwdm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pwdm
    restart: unless-stopped
    ports:
      - "9090:80"   # 프론트엔드 (Nginx)
      - "3000:3000" # 백엔드 API
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      - pwdm-data:/app/backend/data
    networks:
      - akke

networks:
  akke:
    external: true 

volumes:
  pwdm-data:

