version: '3.8'

services:
  pwdm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pwdm
    restart: unless-stopped
    ports:
      - "80:80"     # 프론트엔드 (Nginx)
      - "3000:3000" # 백엔드 API
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      - pwdm-data:/app/backend/data

  # 필요한 경우 MySQL 서비스 추가
  # db:
  #   image: mysql:8.0
  #   container_name: pwdm-db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"

volumes:
  pwdm-data:
  # mysql-data:
